#ifndef ARCTRACKER_ENGINE_VOLUME_MAPPING_TYPE_H
#define ARCTRACKER_ENGINE_VOLUME_MAPPING_TYPE_H

typedef enum { VOLUME_AMIGA, VOLUME_ARCHIMEDES } volume_mapping_type_t;

#endif //ARCTRACKER_ENGINE_VOLUME_MAPPING_TYPE_H
